//! [`LegacyAttacker`] — the 28 legacy attack renderings, ported field for field.
//!
//! # Why faithfully
//!
//! 07-threats-and-detection.md §2.1 says the legacy renderings are "preserved as
//! defaults", and the reason is not sentiment: the legacy corpus — the datasets the
//! machine-learning contract, the foundry elites and every published number in this
//! repository were computed from — was generated by these formulas. A rendering that
//! differs by a metre is a dataset that cannot be reproduced, and the difference would
//! show up as a detector's recall moving for no stated reason.
//!
//! Every branch below therefore cites the legacy symbol it came from, and
//! `tests/legacy_conformance.rs` asserts the constants against numbers read out of
//! `legacy/scms_sim_ref/mock_pipeline/run.py` rather than out of anybody's memory.
//!
//! # What the magnitudes are relative to
//!
//! The legacy `attack_claim` is called with `(mx, my, mspeed, mheading)` — the vehicle's
//! **measured** state, i.e. its GNSS belief, not its true state. This port keeps that:
//! [`crate::attack::AttackerView::honest`] is the node's own belief, so a falsification
//! magnitude here is the size of the lie and nothing in the attacker has ever touched the
//! truth.
//!
//! # The intensity dial
//!
//! `k = attack_intensity × per-type magnitude scale`, folded exactly as the legacy engine
//! folds it: the random draws happen *before* the multiply, so a per-type scale never
//! changes the draw count or the stream position and a run at scale 1.0 is byte-identical
//! to the legacy default.

use std::collections::BTreeMap;

use crate::attack::{
    AttackAction, AttackKind, Attacker, AttackerView, Emission, EventClaim, HonestClaim,
};
use crate::capability::{AttackSchedule, Capabilities, wrap_heading};
use crate::cards::{LEGACY_PY, design, legacy, legacy_param, legacy_uncited};
use crate::ctx::ThreatCtx;
use crate::obs::StationType;
use v2xw_core::card::{
    Determinism, Family, ModelCard, Parameter, Tier, Validation, ValidationStatus,
};
use v2xw_core::ids::NodeId;
use v2xw_core::math;
use v2xw_core::model::Model;
use v2xw_core::rng::{EntityRef, RngDomain};
use v2xw_core::time::{NS_PER_S, SimTime, ns_to_secs, secs_to_ns};

/// The model id every card and every `gt.attack.action` record in this module carries.
pub const MODEL_ID: &str = "threat/attacker/legacy-catalog";

/// The falsification magnitudes, one field per legacy constant.
///
/// Every field is a declared card parameter (invariant I-C3) and every default is the
/// number in `run.py :: attack_claim` or in the broadcast pre-pass around line 2574.
#[derive(Debug, Clone, PartialEq)]
pub struct Magnitudes {
    /// `ConstPosOffset`: metres added to both axes. Legacy `25.0 * k`.
    pub const_pos_offset_m: f64,
    /// `RandomPos` and `DoSRandom`: half-range of the uniform offset. Legacy
    /// `r.uniform(-60, 60) * k`.
    pub random_pos_half_range_m: f64,
    /// `Teleport`: east jump. Legacy `150.0 * k`.
    pub teleport_dx_m: f64,
    /// `Teleport`: north jump. Legacy `80.0 * k`.
    pub teleport_dy_m: f64,
    /// `Teleport`: fires when the integer second is a multiple of this. Legacy
    /// `int(t) % 4 == 0`.
    pub teleport_period_s: u64,
    /// `SineWavePos`: amplitude. Legacy `20.0 * k * sin(0.6 t)`.
    pub sine_pos_amplitude_m: f64,
    /// `SineWavePos`: angular frequency, rad/s. Legacy `0.6`.
    pub sine_pos_omega_rad_s: f64,
    /// `ConstSpeedOffset`: m/s added. Legacy `12.0 * k`.
    pub const_speed_offset_mps: f64,
    /// `RandomSpeed`: upper bound of the claimed speed. Legacy `r.uniform(0, 40)`.
    pub random_speed_max_mps: f64,
    /// `StopAndGo`: the "go" speed; the "stop" phase claims zero. Legacy `35.0`.
    pub stop_and_go_speed_mps: f64,
    /// `HeadingOffset`: degrees added. Legacy `45.0 * k`.
    pub heading_offset_deg: f64,
    /// `DataReplay`: how many claims back the replayed state comes from. Legacy
    /// `v.hist[-5]`.
    pub replay_lag_samples: usize,
    /// `SlowDrift`: metres per second added to the drift rate each step. Legacy
    /// `0.10 * k`.
    pub slow_drift_ramp_mps: f64,
    /// `SlowDrift`: the drift rate's ceiling. Legacy `min(5.0, …)`.
    pub slow_drift_max_rate_mps: f64,
    /// `AlongRoadOffset`: metres along the claimed heading. Legacy `30.0 * k`.
    pub along_road_offset_m: f64,
    /// `Disruptive`: half-range of the position jitter. Legacy `r.uniform(-55, 55) * k`.
    pub disruptive_pos_half_range_m: f64,
    /// `Disruptive`: speed added on even seconds. Legacy `18.0 * k`.
    pub disruptive_speed_up_mps: f64,
    /// `Disruptive`: speed removed on odd seconds. Legacy `-12.0 * k`.
    pub disruptive_speed_down_mps: f64,
    /// `Disruptive`: heading rotation, degrees. Legacy `100.0 * k`.
    pub disruptive_heading_deg: f64,
    /// `PosSpeedInconsistent`: m/s removed from the claimed speed. Legacy `20.0 * k`.
    pub pos_speed_inconsistent_drop_mps: f64,
    /// `PosHeadingInconsistent`: sideways swing amplitude. Legacy `30.0 * k`.
    pub pos_heading_swing_m: f64,
    /// `PosHeadingInconsistent`: swing angular frequency, rad/s. Legacy `1.3`.
    pub pos_heading_omega_rad_s: f64,
    /// `EventualStop`: how long after onset the claimed position freezes. Legacy
    /// `(t - v.attack_from) >= 6.0`.
    pub eventual_stop_delay_s: f64,
    /// `EventualStop`: the residual creeping speed's constant term. Legacy `0.8`.
    pub eventual_stop_base_speed_mps: f64,
    /// `EventualStop`: the residual creeping speed's scaled term. Legacy `2.0 * k`.
    pub eventual_stop_scale_mps: f64,
    /// `VruPositionSpoof`: the plausible VRU crawl it claims. Legacy `cs = 2.0`.
    pub vru_spoof_speed_mps: f64,
    /// `VruPositionSpoof`: the radius of the circle its claimed position walks. Legacy
    /// `60.0 * k`.
    pub vru_spoof_radius_m: f64,
    /// `VruPositionSpoof`: the circle's angular frequency, rad/s. Legacy `ang = 2.0 * t`.
    pub vru_spoof_omega_rad_s: f64,
}

impl Default for Magnitudes {
    fn default() -> Self {
        Self {
            const_pos_offset_m: 25.0,
            random_pos_half_range_m: 60.0,
            teleport_dx_m: 150.0,
            teleport_dy_m: 80.0,
            teleport_period_s: 4,
            sine_pos_amplitude_m: 20.0,
            sine_pos_omega_rad_s: 0.6,
            const_speed_offset_mps: 12.0,
            random_speed_max_mps: 40.0,
            stop_and_go_speed_mps: 35.0,
            heading_offset_deg: 45.0,
            replay_lag_samples: 5,
            slow_drift_ramp_mps: 0.10,
            slow_drift_max_rate_mps: 5.0,
            along_road_offset_m: 30.0,
            disruptive_pos_half_range_m: 55.0,
            disruptive_speed_up_mps: 18.0,
            disruptive_speed_down_mps: 12.0,
            disruptive_heading_deg: 100.0,
            pos_speed_inconsistent_drop_mps: 20.0,
            pos_heading_swing_m: 30.0,
            pos_heading_omega_rad_s: 1.3,
            eventual_stop_delay_s: 6.0,
            eventual_stop_base_speed_mps: 0.8,
            eventual_stop_scale_mps: 2.0,
            vru_spoof_speed_mps: 2.0,
            vru_spoof_radius_m: 60.0,
            vru_spoof_omega_rad_s: 2.0,
        }
    }
}

/// Everything the attacker reads that is not a falsification magnitude.
#[derive(Debug, Clone, PartialEq)]
pub struct LegacyAttackerParams {
    /// Which attack this node runs.
    pub kind: AttackKind,
    /// The global intensity dial (`PipelineConfig.attack_intensity`, default 1.0).
    pub intensity: f64,
    /// Per-type magnitude multipliers, applied on top of [`Self::intensity`]
    /// (`PipelineConfig.attack_magnitude_scale`).
    pub magnitude_scale: BTreeMap<AttackKind, f64>,
    /// The generation interval, seconds (`PipelineConfig.dt`, default 1.0). The drift
    /// integrator and the replay generation-time lag are expressed in it.
    pub dt_s: f64,
    /// The falsification magnitudes.
    pub magnitudes: Magnitudes,
    /// Copies a flooding attacker puts on the air per interval
    /// (`PipelineConfig.dos_burst`, default 12).
    pub dos_burst: u32,
    /// Staleness a `DelayedMessages` attacker stamps, seconds
    /// (`PipelineConfig.delay_s`, default 6.0). `OutOfOrder` draws uniformly in
    /// `[delay_s, 2 delay_s]`.
    pub delay_s: f64,
    /// How far in the past an `ExpiredCert` attacker's certificate expired, seconds.
    /// Legacy `cvt = t - 5.0`.
    pub expired_cert_lag_s: f64,
    /// How far in the future a `NotYetValid` attacker's certificate becomes valid,
    /// seconds. Legacy `cvf = t + 5.0`.
    pub not_yet_valid_lead_s: f64,
    /// Ghost identities a `Sybil` attacker transmits from
    /// (`PipelineConfig.sybil_ghosts`, default 6).
    pub sybil_ghosts: u32,
    /// Half-range of the jitter each ghost's claimed position gets around the attacker's
    /// own claim, metres. Legacy `sr.uniform(-1, 1)`.
    pub sybil_jitter_m: f64,
    /// Phantom event messages a `FakeHazard` attacker emits per
    /// [`Self::denm_rate_window_s`] (`PipelineConfig.denm_fake_fallback_rate`, 40.0).
    pub denm_fake_rate: f64,
    /// The window the DENM rate is expressed per, seconds
    /// (`PipelineConfig.denm_rate_window_s`, 100.0).
    pub denm_rate_window_s: f64,
    /// The cause code a `FakeHazard` attacker announces.
    pub denm_event_type: String,
    /// The probability a `SelectiveDrop` attacker drops a message it should forward.
    ///
    /// No legacy value: the legacy engine had no forwarding role. `todo-calibrate`.
    pub selective_drop_prob: f64,
}

impl Default for LegacyAttackerParams {
    fn default() -> Self {
        Self {
            kind: AttackKind::ConstPos,
            intensity: 1.0,
            magnitude_scale: BTreeMap::new(),
            dt_s: 1.0,
            magnitudes: Magnitudes::default(),
            dos_burst: 12,
            delay_s: 6.0,
            expired_cert_lag_s: 5.0,
            not_yet_valid_lead_s: 5.0,
            sybil_ghosts: 6,
            sybil_jitter_m: 1.0,
            denm_fake_rate: 40.0,
            denm_rate_window_s: 100.0,
            denm_event_type: "emergencyElectronicBrakeLight".to_string(),
            selective_drop_prob: 0.5,
        }
    }
}

/// A magnitude scale was asked for on a type that has no amplitude.
#[derive(Debug, Clone, PartialEq, Eq, thiserror::Error)]
#[error(
    "attack type {kind} has no falsification magnitude to scale (fixed or honest); \
     to drop a type, leave it out of the attack mix rather than scaling it to zero"
)]
pub struct UnscalableMagnitude {
    /// The type that was asked for.
    pub kind: String,
}

impl LegacyAttackerParams {
    /// The parameters for one attack type, everything else at the legacy default.
    #[must_use]
    pub fn new(kind: AttackKind) -> Self {
        Self {
            kind,
            ..Self::default()
        }
    }

    /// Adds a per-type magnitude multiplier.
    ///
    /// # Errors
    /// [`UnscalableMagnitude`] when the type has no amplitude
    /// ([`AttackKind::is_magnitude_scalable`]), or when `scale` is not strictly positive.
    /// The legacy engine raises on both rather than silently no-opping, "so the control is
    /// honest" (`run.py :: _parse_magnitude_scale`).
    pub fn with_magnitude_scale(
        mut self,
        kind: AttackKind,
        scale: f64,
    ) -> Result<Self, UnscalableMagnitude> {
        let bad_scale = !scale.is_finite() || scale <= 0.0;
        if !kind.is_magnitude_scalable() || bad_scale {
            return Err(UnscalableMagnitude {
                kind: kind.as_str().to_string(),
            });
        }
        self.magnitude_scale.insert(kind, scale);
        Ok(self)
    }

    /// The intensity dial folded with this type's own scale: the legacy `k`.
    #[must_use]
    pub fn k(&self) -> f64 {
        self.intensity * self.magnitude_scale.get(&self.kind).copied().unwrap_or(1.0)
    }
}

/// The per-node state the renderings carry between messages.
#[derive(Debug, Clone, Default, PartialEq)]
struct AttackerState {
    /// `ConstPos` / `EventualStop`: the frozen claimed position.
    frozen: Option<(f64, f64)>,
    /// `SlowDrift`: the accumulated offset and its ramping rate.
    drift_m: f64,
    drift_rate_mps: f64,
    /// `DataReplay`: the last claims, newest last.
    history: Vec<HonestClaim>,
    /// The first instant this attacker acted, for `EventualStop`'s delay.
    onset: Option<SimTime>,
    /// CRL-aware evasion: revocations already seen and the instant dormancy ends.
    crl_seen: u32,
    dormant_until: SimTime,
}

/// The legacy attack catalog as one swappable attacker model.
#[derive(Debug, Clone)]
pub struct LegacyAttacker {
    card: ModelCard,
    params: LegacyAttackerParams,
    capabilities: Capabilities,
    schedule: AttackSchedule,
    node: NodeId,
    ghost_signers: Vec<[u8; 8]>,
    state: AttackerState,
}

impl LegacyAttacker {
    /// An attacker at `node` running `params`, with the given capabilities and schedule.
    ///
    /// `ghost_signers` are the extra concurrent credentials a `Sybil` attacker transmits
    /// from. They are credentials the attacker *holds*: 07-threats §2.2's ghost-vehicle
    /// attack uses `Own(n)` or `Stolen`, and the engine's credential store is what issues
    /// them, so an attacker declared `CredentialAccess::None` gets no ghosts.
    #[must_use]
    pub fn new(
        node: NodeId,
        params: LegacyAttackerParams,
        capabilities: Capabilities,
        schedule: AttackSchedule,
        ghost_signers: Vec<[u8; 8]>,
    ) -> Self {
        let card = card(&params);
        Self {
            card,
            params,
            capabilities,
            schedule,
            node,
            ghost_signers,
            state: AttackerState::default(),
        }
    }

    /// The attack this model renders.
    #[must_use]
    pub fn kind(&self) -> AttackKind {
        self.params.kind
    }

    /// The parameters it reads.
    #[must_use]
    pub fn params(&self) -> &LegacyAttackerParams {
        &self.params
    }

    /// The instant dormancy ends, for a CRL-aware attacker. Zero when it is not dormant.
    #[must_use]
    pub fn dormant_until(&self) -> SimTime {
        self.state.dormant_until
    }

    /// The legacy `attack_claim`, rendering the position/speed/heading edit.
    ///
    /// Returns the falsified `(x, y, speed, heading)`. Ported branch for branch from
    /// `run.py :: attack_claim`; see the per-branch citations there.
    fn attack_claim(
        &mut self,
        ctx: &mut dyn ThreatCtx,
        t: SimTime,
        honest: HonestClaim,
    ) -> (f64, f64, f64, f64) {
        let m = &self.params.magnitudes;
        let k = self.params.k();
        let scale = self
            .params
            .magnitude_scale
            .get(&self.params.kind)
            .copied()
            .unwrap_or(1.0);
        let t_s = ns_to_secs(t);
        let t_int = t / NS_PER_S;
        let (mx, my, mspeed, mheading) =
            (honest.x_m, honest.y_m, honest.speed_mps, honest.heading_rad);
        let (mut cx, mut cy, mut cs, mut ch) = (mx, my, mspeed, mheading);
        let entity = EntityRef::Node(self.node);

        match self.params.kind {
            AttackKind::ConstPos => {
                let f = *self.state.frozen.get_or_insert((mx, my));
                cx = f.0;
                cy = f.1;
            }
            AttackKind::ConstPosOffset => {
                cx = mx + m.const_pos_offset_m * k;
                cy = my + m.const_pos_offset_m * k;
            }
            AttackKind::RandomPos | AttackKind::DoSRandom => {
                let h = m.random_pos_half_range_m;
                let mut rng = ctx.rng(RngDomain::Attack, entity);
                let dx = rng.uniform(-h, h);
                let dy = rng.uniform(-h, h);
                drop(rng);
                cx = mx + dx * k;
                cy = my + dy * k;
            }
            AttackKind::Teleport => {
                if m.teleport_period_s > 0 && t_int % m.teleport_period_s == 0 {
                    cx = mx + m.teleport_dx_m * k;
                    cy = my + m.teleport_dy_m * k;
                }
            }
            AttackKind::SineWavePos => {
                cy = my + m.sine_pos_amplitude_m * k * math::sin(m.sine_pos_omega_rad_s * t_s);
            }
            AttackKind::ConstSpeedOffset => cs = mspeed + m.const_speed_offset_mps * k,
            AttackKind::RandomSpeed => {
                // The draw is unconditional, so the stream position never depends on the
                // scale; at scale 1.0 the claimed speed is the historic absolute value.
                let mut rng = ctx.rng(RngDomain::Attack, entity);
                let u = rng.uniform(0.0, m.random_speed_max_mps);
                drop(rng);
                cs = if scale == 1.0 {
                    u
                } else {
                    (mspeed + (u - mspeed) * scale).max(0.0)
                };
            }
            AttackKind::StopAndGo => {
                let go = if t_int % 2 == 0 {
                    0.0
                } else {
                    m.stop_and_go_speed_mps
                };
                cs = if scale == 1.0 {
                    go
                } else {
                    (mspeed + (go - mspeed) * scale).max(0.0)
                };
            }
            AttackKind::ReversedHeading => ch = wrap_heading(mheading + core::f64::consts::PI),
            AttackKind::HeadingOffset => {
                ch = wrap_heading(mheading + (m.heading_offset_deg * k).to_radians());
            }
            AttackKind::DataReplay => {
                let n = self.state.history.len();
                if n >= m.replay_lag_samples {
                    let old = self.state.history[n - m.replay_lag_samples];
                    cx = old.x_m;
                    cy = old.y_m;
                    cs = old.speed_mps;
                    ch = old.heading_rad;
                }
            }
            AttackKind::SlowDrift => {
                self.state.drift_rate_mps = (self.state.drift_rate_mps + m.slow_drift_ramp_mps * k)
                    .min(m.slow_drift_max_rate_mps);
                self.state.drift_m += self.state.drift_rate_mps * self.params.dt_s;
                cx = mx + self.state.drift_m;
            }
            AttackKind::AlongRoadOffset => {
                let (s, c) = math::sin_cos(mheading);
                cx = mx + m.along_road_offset_m * k * c;
                cy = my + m.along_road_offset_m * k * s;
            }
            AttackKind::Disruptive => {
                let h = m.disruptive_pos_half_range_m;
                let mut rng = ctx.rng(RngDomain::Attack, entity);
                let dx = rng.uniform(-h, h);
                let dy = rng.uniform(-h, h);
                drop(rng);
                cx = mx + dx * k;
                cy = my + dy * k;
                let dv = if t_int % 2 == 0 {
                    m.disruptive_speed_up_mps
                } else {
                    -m.disruptive_speed_down_mps
                };
                cs = (mspeed + dv * k).max(0.0);
                ch = wrap_heading(mheading + (m.disruptive_heading_deg * k).to_radians());
            }
            AttackKind::PosSpeedInconsistent => {
                cs = (mspeed - m.pos_speed_inconsistent_drop_mps * k).max(0.0);
            }
            AttackKind::PosHeadingInconsistent => {
                let perp = mheading + core::f64::consts::FRAC_PI_2;
                let swing = m.pos_heading_swing_m * k * math::sin(m.pos_heading_omega_rad_s * t_s);
                let (s, c) = math::sin_cos(perp);
                cx = mx + swing * c;
                cy = my + swing * s;
                ch = mheading;
            }
            AttackKind::EventualStop => {
                let onset = self.state.onset.unwrap_or(t);
                if ns_to_secs(t.saturating_sub(onset)) >= m.eventual_stop_delay_s {
                    let f = *self.state.frozen.get_or_insert((mx, my));
                    cx = f.0;
                    cy = f.1;
                    cs = m.eventual_stop_base_speed_mps + m.eventual_stop_scale_mps * k;
                }
            }
            AttackKind::VruPositionSpoof => {
                cs = m.vru_spoof_speed_mps;
                let ang = m.vru_spoof_omega_rad_s * t_s;
                let (s, c) = math::sin_cos(ang);
                cx = mx + m.vru_spoof_radius_m * k * c;
                cy = my + m.vru_spoof_radius_m * k * s;
            }
            // `VruImpersonation` and `FakeHazard` drive honestly: the first falsifies only
            // its declared station type, the second only emits a phantom event message.
            // `Sybil`, `DoS`, the credential and timing types and `SelectiveDrop` do not
            // touch these four fields either.
            AttackKind::VruImpersonation
            | AttackKind::FakeHazard
            | AttackKind::Sybil
            | AttackKind::DoS
            | AttackKind::DelayedMessages
            | AttackKind::OutOfOrder
            | AttackKind::InvalidSignature
            | AttackKind::ExpiredCert
            | AttackKind::NotYetValid
            | AttackKind::SelectiveDrop => {}
        }
        (cx, cy, cs, ch)
    }
}

impl Model for LegacyAttacker {
    fn card(&self) -> &ModelCard {
        &self.card
    }
}

impl Attacker for LegacyAttacker {
    fn capabilities(&self) -> &Capabilities {
        &self.capabilities
    }

    fn schedule(&self) -> &AttackSchedule {
        &self.schedule
    }

    fn observe(&mut self, _ctx: &mut dyn ThreatCtx, view: &AttackerView<'_>) {
        // CRL-aware evasion (`run.py`, the broadcast pre-pass): an attacker that watches
        // the PUBLIC CRL goes dormant for a while after an accomplice is revoked, which
        // starves the authority's sustained-evidence gate. `crl_revocations_seen` is
        // `None` unless the attacker declared the knowledge, so an attacker that did not
        // declare it cannot evade this way.
        if !self.capabilities.knowledge.crl {
            return;
        }
        if let Some(seen) = view.crl_revocations_seen
            && seen > self.state.crl_seen
        {
            self.state.crl_seen = seen;
            self.state.dormant_until = self.schedule.crl_dormant.after(view.believed_time);
        }
    }

    fn act(
        &mut self,
        ctx: &mut dyn ThreatCtx,
        view: &AttackerView<'_>,
        out: &mut Emission,
    ) -> Vec<AttackAction> {
        let t = view.believed_time;
        let honest = view.honest;
        let active = self
            .schedule
            .active_at(t, view.own_belief.x_m, view.own_belief.y_m)
            && t >= self.state.dormant_until;
        if !active {
            // An inactive attacker is an ordinary node, and its history keeps filling so
            // that a `DataReplay` attacker has something to replay when it wakes up —
            // which is what the legacy engine does (`tx.hist.append` sits outside the
            // `if attacking` branch).
            self.state.history.push(honest);
            self.trim_history();
            return Vec::new();
        }
        if self.state.onset.is_none() {
            self.state.onset = Some(t);
        }

        let mut actions = Vec::new();
        let p_dt = self.params.dt_s;
        let (cx, cy, cs, ch) = self.attack_claim(ctx, t, honest);
        let mut fields: Vec<String> = Vec::new();
        let dpos = math::hypot(cx - honest.x_m, cy - honest.y_m);
        if dpos > 0.0 {
            fields.push("position".to_string());
        }
        if cs != honest.speed_mps {
            fields.push("speed".to_string());
        }
        if ch != honest.heading_rad {
            fields.push("heading".to_string());
        }
        out.x_m = cx;
        out.y_m = cy;
        out.speed_mps = cs;
        out.heading_rad = ch;

        // Timing and envelope edits: the legacy broadcast pre-pass, in its order.
        match self.params.kind {
            AttackKind::DoS | AttackKind::DoSRandom => {
                out.repetitions = self.params.dos_burst;
                fields.push("repetitions".to_string());
            }
            AttackKind::DelayedMessages => {
                out.generation_time = t.saturating_sub(secs_to_ns(self.params.delay_s));
                actions.push(AttackAction::Delay {
                    seconds: self.params.delay_s,
                });
            }
            AttackKind::DataReplay => {
                let age = self.params.magnitudes.replay_lag_samples as f64 * p_dt;
                out.generation_time = t.saturating_sub(secs_to_ns(age));
                actions.push(AttackAction::Replay { age_s: age });
            }
            AttackKind::OutOfOrder => {
                let d = self.params.delay_s;
                let mut rng = ctx.rng(RngDomain::Attack, EntityRef::Node(self.node));
                let lag = rng.uniform(d, 2.0 * d);
                drop(rng);
                out.generation_time = t.saturating_sub(secs_to_ns(lag));
                actions.push(AttackAction::Delay { seconds: lag });
            }
            AttackKind::InvalidSignature => {
                out.signature_valid = false;
                fields.push("signature".to_string());
            }
            AttackKind::ExpiredCert => {
                out.cert_valid_to = t.saturating_sub(secs_to_ns(self.params.expired_cert_lag_s));
                fields.push("certificate".to_string());
            }
            AttackKind::NotYetValid => {
                out.cert_valid_from = t + secs_to_ns(self.params.not_yet_valid_lead_s);
                fields.push("certificate".to_string());
            }
            AttackKind::SelectiveDrop => {
                let mut rng = ctx.rng(RngDomain::Attack, EntityRef::Node(self.node));
                let drop_it = rng.bool(self.params.selective_drop_prob);
                drop(rng);
                if drop_it {
                    out.suppressed = true;
                    actions.push(AttackAction::Suppress);
                }
            }
            _ => {}
        }

        // The self-declared station type (an MA-visible field a sender simply asserts).
        if matches!(
            self.params.kind,
            AttackKind::VruImpersonation | AttackKind::VruPositionSpoof
        ) {
            out.station_type = StationType::Vru;
            fields.push("station_type".to_string());
        }

        if !fields.is_empty() {
            fields.sort_unstable();
            let magnitude = principal_magnitude(&fields, dpos, cs - honest.speed_mps, ch, honest);
            actions.push(AttackAction::FalsifyOutgoing { fields, magnitude });
        }

        // Phantom event message: an honest beacon announcing a hazard its own claimed
        // kinematics contradict.
        if self.params.kind == AttackKind::FakeHazard {
            let p = (self.params.denm_fake_rate * p_dt / self.params.denm_rate_window_s)
                .clamp(0.0, 1.0);
            let mut rng = ctx.rng(
                RngDomain::Attack,
                EntityRef::custom(MODEL_ID, u64::from(self.node.index())),
            );
            let fire = rng.bool(p);
            drop(rng);
            if fire {
                out.events.push(EventClaim {
                    event_type: self.params.denm_event_type.clone(),
                    x_m: out.x_m,
                    y_m: out.y_m,
                    claimed_speed_mps: out.speed_mps,
                });
                actions.push(AttackAction::ForgeEvent {
                    event_type: self.params.denm_event_type.clone(),
                });
            }
        }

        // Sybil ghosts: concurrent valid pseudonyms this node holds, each claiming a
        // position within a metre of the attacker's own claim, with its speed and heading.
        if self.params.kind == AttackKind::Sybil {
            let n = (self.params.sybil_ghosts as usize).min(self.ghost_signers.len());
            let j = self.params.sybil_jitter_m;
            for i in 0..n {
                let signer = self.ghost_signers[i];
                let mut rng = ctx.rng(RngDomain::Attack, EntityRef::Node(self.node));
                let dx = rng.uniform(-j, j);
                let dy = rng.uniform(-j, j);
                drop(rng);
                let mut ghost = out.clone();
                ghost.signer = signer;
                ghost.x_m = out.x_m + dx;
                ghost.y_m = out.y_m + dy;
                ghost.ghosts = Vec::new();
                ghost.events = Vec::new();
                out.ghosts.push(ghost);
                actions.push(AttackAction::Ghost { signer });
            }
        }

        self.state.history.push(HonestClaim {
            x_m: out.x_m,
            y_m: out.y_m,
            speed_mps: out.speed_mps,
            heading_rad: out.heading_rad,
        });
        self.trim_history();
        actions
    }
}

impl LegacyAttacker {
    /// Keeps the replay history bounded: one more than the replay lag is all a rendering
    /// ever reads.
    fn trim_history(&mut self) {
        let keep = self.params.magnitudes.replay_lag_samples + 1;
        if self.state.history.len() > keep {
            let excess = self.state.history.len() - keep;
            self.state.history.drain(..excess);
        }
    }
}

/// The magnitude the ground-truth record carries for a falsification: the principal
/// field's edit, in that field's own units.
fn principal_magnitude(
    fields: &[String],
    dpos_m: f64,
    dspeed_mps: f64,
    claimed_heading_rad: f64,
    honest: HonestClaim,
) -> f64 {
    if fields.iter().any(|f| f == "position") {
        dpos_m
    } else if fields.iter().any(|f| f == "speed") {
        dspeed_mps.abs()
    } else if fields.iter().any(|f| f == "heading") {
        crate::capability::angle_diff_rad(claimed_heading_rad, honest.heading_rad).to_degrees()
    } else {
        0.0
    }
}

/// The model card for a [`LegacyAttacker`] rendering `params.kind`.
///
/// Every numeric field of [`LegacyAttackerParams`] and [`Magnitudes`] is declared here
/// (invariant I-C3), each citing the legacy symbol it was read out of.
#[must_use]
pub fn card(params: &LegacyAttackerParams) -> ModelCard {
    use serde_json::json;
    let m = &params.magnitudes;
    let mut card = ModelCard::new(
        MODEL_ID,
        Family::Attacker,
        "1.0.0",
        format!(
            "The legacy attack catalog as a swappable attacker: renders the {} attack \
             ({} family) by editing the outgoing claim before signing.",
            params.kind,
            params.kind.family().as_str()
        ),
    );
    card.tier = vec![Tier::Abstract, Tier::Medium, Tier::High];
    card.equations = vec![
        v2xw_core::card::Equation::new(
            "intensity dial",
            "k = attack_intensity × magnitude_scale[type]; every magnitude below is × k",
        ),
        v2xw_core::card::Equation::new(
            "slow drift",
            "rate ← min(rate + 0.10 k, 5.0); drift ← drift + rate·dt; x_claimed = x + drift",
        ),
        v2xw_core::card::Equation::new(
            "falsified label",
            "|Δpos| > 1 m ∨ |Δspeed| > 1 m/s ∨ |Δheading| > 5° ∨ repetitions > 1 ∨ \
             generation_time < now ∨ ¬sig_valid ∨ cert outside [from−1 s, to+1 s] ∨ \
             declared station type ≠ true station type",
        ),
    ];
    let mut p: Vec<Parameter> = vec![
        legacy_param(
            "attack_intensity",
            "-",
            json!(params.intensity),
            LEGACY_PY,
            "PipelineConfig.attack_intensity",
        ),
        legacy_param(
            "dt_s",
            "s",
            json!(params.dt_s),
            LEGACY_PY,
            "PipelineConfig.dt",
        ),
        legacy_param(
            "const_pos_offset_m",
            "m",
            json!(m.const_pos_offset_m),
            LEGACY_PY,
            "attack_claim :: ConstPosOffset",
        ),
        legacy_param(
            "random_pos_half_range_m",
            "m",
            json!(m.random_pos_half_range_m),
            LEGACY_PY,
            "attack_claim :: RandomPos",
        ),
        legacy_param(
            "teleport_dx_m",
            "m",
            json!(m.teleport_dx_m),
            LEGACY_PY,
            "attack_claim :: Teleport",
        ),
        legacy_param(
            "teleport_dy_m",
            "m",
            json!(m.teleport_dy_m),
            LEGACY_PY,
            "attack_claim :: Teleport",
        ),
        legacy_param(
            "teleport_period_s",
            "s",
            json!(m.teleport_period_s),
            LEGACY_PY,
            "attack_claim :: Teleport (int(t) % 4)",
        ),
        legacy_param(
            "sine_pos_amplitude_m",
            "m",
            json!(m.sine_pos_amplitude_m),
            LEGACY_PY,
            "attack_claim :: SineWavePos",
        ),
        legacy_param(
            "sine_pos_omega_rad_s",
            "rad/s",
            json!(m.sine_pos_omega_rad_s),
            LEGACY_PY,
            "attack_claim :: SineWavePos",
        ),
        legacy_param(
            "const_speed_offset_mps",
            "m/s",
            json!(m.const_speed_offset_mps),
            LEGACY_PY,
            "attack_claim :: ConstSpeedOffset",
        ),
        legacy_param(
            "random_speed_max_mps",
            "m/s",
            json!(m.random_speed_max_mps),
            LEGACY_PY,
            "attack_claim :: RandomSpeed",
        ),
        legacy_param(
            "stop_and_go_speed_mps",
            "m/s",
            json!(m.stop_and_go_speed_mps),
            LEGACY_PY,
            "attack_claim :: StopAndGo",
        ),
        legacy_param(
            "heading_offset_deg",
            "deg",
            json!(m.heading_offset_deg),
            LEGACY_PY,
            "attack_claim :: HeadingOffset",
        ),
        legacy_param(
            "replay_lag_samples",
            "-",
            json!(m.replay_lag_samples),
            LEGACY_PY,
            "attack_claim :: DataReplay (v.hist[-5])",
        ),
        legacy_param(
            "slow_drift_ramp_mps",
            "m/s",
            json!(m.slow_drift_ramp_mps),
            LEGACY_PY,
            "attack_claim :: SlowDrift",
        ),
        legacy_param(
            "slow_drift_max_rate_mps",
            "m/s",
            json!(m.slow_drift_max_rate_mps),
            LEGACY_PY,
            "attack_claim :: SlowDrift",
        ),
        legacy_param(
            "along_road_offset_m",
            "m",
            json!(m.along_road_offset_m),
            LEGACY_PY,
            "attack_claim :: AlongRoadOffset",
        ),
        legacy_param(
            "disruptive_pos_half_range_m",
            "m",
            json!(m.disruptive_pos_half_range_m),
            LEGACY_PY,
            "attack_claim :: Disruptive",
        ),
        legacy_param(
            "disruptive_speed_up_mps",
            "m/s",
            json!(m.disruptive_speed_up_mps),
            LEGACY_PY,
            "attack_claim :: Disruptive",
        ),
        legacy_param(
            "disruptive_speed_down_mps",
            "m/s",
            json!(m.disruptive_speed_down_mps),
            LEGACY_PY,
            "attack_claim :: Disruptive",
        ),
        legacy_param(
            "disruptive_heading_deg",
            "deg",
            json!(m.disruptive_heading_deg),
            LEGACY_PY,
            "attack_claim :: Disruptive",
        ),
        legacy_param(
            "pos_speed_inconsistent_drop_mps",
            "m/s",
            json!(m.pos_speed_inconsistent_drop_mps),
            LEGACY_PY,
            "attack_claim :: PosSpeedInconsistent",
        ),
        legacy_param(
            "pos_heading_swing_m",
            "m",
            json!(m.pos_heading_swing_m),
            LEGACY_PY,
            "attack_claim :: PosHeadingInconsistent",
        ),
        legacy_param(
            "pos_heading_omega_rad_s",
            "rad/s",
            json!(m.pos_heading_omega_rad_s),
            LEGACY_PY,
            "attack_claim :: PosHeadingInconsistent",
        ),
        legacy_param(
            "eventual_stop_delay_s",
            "s",
            json!(m.eventual_stop_delay_s),
            LEGACY_PY,
            "attack_claim :: EventualStop",
        ),
        legacy_param(
            "eventual_stop_base_speed_mps",
            "m/s",
            json!(m.eventual_stop_base_speed_mps),
            LEGACY_PY,
            "attack_claim :: EventualStop",
        ),
        legacy_param(
            "eventual_stop_scale_mps",
            "m/s",
            json!(m.eventual_stop_scale_mps),
            LEGACY_PY,
            "attack_claim :: EventualStop",
        ),
        legacy_param(
            "vru_spoof_speed_mps",
            "m/s",
            json!(m.vru_spoof_speed_mps),
            LEGACY_PY,
            "attack_claim :: VruPositionSpoof",
        ),
        legacy_param(
            "vru_spoof_radius_m",
            "m",
            json!(m.vru_spoof_radius_m),
            LEGACY_PY,
            "attack_claim :: VruPositionSpoof",
        ),
        legacy_param(
            "vru_spoof_omega_rad_s",
            "rad/s",
            json!(m.vru_spoof_omega_rad_s),
            LEGACY_PY,
            "attack_claim :: VruPositionSpoof",
        ),
        legacy_uncited(
            "dos_burst",
            "msg/interval",
            json!(params.dos_burst),
            LEGACY_PY,
            "PipelineConfig.dos_burst",
            "measure what a saturated ITS-G5 transmitter can actually emit per CAM \
             interval under the node's own DCC and HSM budget (06-node-models.md §3), \
             and set the burst to that rather than to a round number.",
        ),
        legacy_uncited(
            "delay_s",
            "s",
            json!(params.delay_s),
            LEGACY_PY,
            "PipelineConfig.delay_s",
            "choose against the 1609.2 generation-time acceptance window rather than \
             independently of it, so the attack is defined relative to the check it \
             defeats.",
        ),
        legacy_param(
            "expired_cert_lag_s",
            "s",
            json!(params.expired_cert_lag_s),
            LEGACY_PY,
            "broadcast pre-pass :: ExpiredCert (cvt = t - 5.0)",
        ),
        legacy_param(
            "not_yet_valid_lead_s",
            "s",
            json!(params.not_yet_valid_lead_s),
            LEGACY_PY,
            "broadcast pre-pass :: NotYetValid (cvf = t + 5.0)",
        ),
        legacy_param(
            "sybil_ghosts",
            "-",
            json!(params.sybil_ghosts),
            LEGACY_PY,
            "PipelineConfig.sybil_ghosts",
        ),
        legacy_param(
            "sybil_jitter_m",
            "m",
            json!(params.sybil_jitter_m),
            LEGACY_PY,
            "broadcast pre-pass :: Sybil (sr.uniform(-1, 1))",
        ),
        legacy_param(
            "denm_fake_rate",
            "msg/window",
            json!(params.denm_fake_rate),
            LEGACY_PY,
            "DENM_FAKE_FALLBACK_RATE",
        ),
        legacy_param(
            "denm_rate_window_s",
            "s",
            json!(params.denm_rate_window_s),
            LEGACY_PY,
            "DENM_RATE_WINDOW_S",
        ),
    ];
    let mut drop_p = Parameter::new(
        "selective_drop_prob",
        "-",
        json!(params.selective_drop_prob),
        v2xw_core::card::Source::todo_calibrate(
            "no legacy value: the legacy engine had no forwarding role",
        ),
    );
    drop_p.range = Some(vec![json!(0.0), json!(1.0)]);
    drop_p.calibration = Some(
        "sweep against the GeoNetworking forwarding and DENM keep-alive models once \
         v2xw-net exposes a forwarding role, and report the drop rate at which \
         multi-hop delivery degrades measurably rather than picking a probability."
            .to_string(),
    );
    p.push(drop_p);
    card.parameters = p;
    card.sources = vec![
        legacy(LEGACY_PY, "attack_claim + the broadcast pre-pass"),
        design("07-threats-and-detection.md §2.1"),
    ];
    card.assumptions = vec![
        "The attacker falsifies relative to its own GNSS belief, not to the truth: it \
         cannot know its own true position any better than an honest node can \
         (invariant I-T1)."
            .to_string(),
        "An attacker's body moves honestly. Only its claims are falsified; there is no \
         mobility control here (07-threats-and-detection.md §1, 'Position')."
            .to_string(),
        "Ghost transmissions use credentials the attacker actually holds, so a Sybil \
         attacker is bounded by its declared concurrent-pseudonym count."
            .to_string(),
    ];
    card.limitations = vec![
        "Renders one attack type per attacker. A node that switches type mid-run is a \
         scenario with two attacker instances, not a parameter here."
            .to_string(),
        "PHY jamming (07-threats-and-detection.md §2.2) is not rendered: it needs the \
         interferer hook in the SINR sum (04-models.md §12.3), which v2xw-radio does not \
         expose yet. Declared as a capability, left unimplemented on purpose."
            .to_string(),
        "Misbehaviour-report poisoning is rendered by the reporting path \
         (crate::report::forge), not here."
            .to_string(),
    ];
    card.determinism = Determinism {
        uses_rng: true,
        rng_domains: vec![RngDomain::Attack.as_str().to_string()],
    };
    card.validation = Validation {
        status: ValidationStatus::UnitTested,
        references: vec![legacy(LEGACY_PY, "attack_claim")],
        tests: vec![
            "legacy_conformance::every_attack_renders_the_documented_deviation".to_string(),
            "attacks::each_attack_touches_only_its_own_fields".to_string(),
        ],
    };
    card
}
