"""Typed stubs for the native module (03-interfaces.md §15: the SDK ships typed stubs).

Hand-written, because the native module is built by a macro and there is no generator that
would produce these from the Rust signatures. That makes them a second description of the
same surface and therefore a thing that can drift; `python/tests/test_stubs.py` checks that
every name here exists on the module and that no public name on the module is missing here,
which catches the drift that matters.
"""

from typing import Any, Dict, Iterable, List, Optional, Sequence, Tuple

__version__: str

class V2xwError(Exception): ...
class ScenarioError(V2xwError): ...
class RecordingError(V2xwError): ...
class MetricError(V2xwError): ...
class DeterminismError(V2xwError): ...

class Scenario:
    @staticmethod
    def load(path: str) -> "Scenario": ...
    @staticmethod
    def parse(text: str, base_dir: Optional[str] = ...) -> "Scenario": ...
    @staticmethod
    def from_dict(doc: Dict[str, Any]) -> "Scenario": ...
    @staticmethod
    def minimal() -> "Scenario": ...
    @property
    def schema(self) -> str: ...
    @property
    def name(self) -> str: ...
    @property
    def seed(self) -> int: ...
    @property
    def duration_s(self) -> float: ...
    @property
    def path(self) -> Optional[str]: ...
    @property
    def content_hash(self) -> str: ...
    def problems(self) -> List[str]: ...
    def validate(self) -> "Scenario": ...
    def to_yaml(self) -> str: ...
    def to_json(self) -> str: ...
    def as_dict(self) -> Dict[str, Any]: ...
    def write(self, path: str) -> None: ...

class Metrics:
    def __len__(self) -> int: ...
    def names(self) -> List[str]: ...
    def arrow(self) -> Any: ...
    def ipc(self) -> bytes: ...
    def write_arrow(self, path: str) -> int: ...
    def rows(self, metric: Optional[str] = ...) -> List[Dict[str, Any]]: ...
    def series(self, metric: str) -> List[Tuple[int, float]]: ...
    def last(self, metric: str) -> Optional[float]: ...
    def summary(self) -> Dict[str, Any]: ...
    @property
    def digest(self) -> str: ...
    def diagnostics(self) -> Dict[str, Any]: ...

class Run:
    @property
    def manifest(self) -> Dict[str, Any]: ...
    @property
    def report(self) -> Dict[str, Any]: ...
    @property
    def metrics(self) -> Metrics: ...
    @property
    def recording(self) -> Optional[str]: ...
    @property
    def end_ns(self) -> int: ...
    @property
    def records(self) -> int: ...
    @property
    def records_refused(self) -> int: ...
    @property
    def scenario_hash(self) -> str: ...

class Recording:
    @staticmethod
    def open(path: str) -> "Recording": ...
    @staticmethod
    def open_bytes(data: bytes) -> "Recording": ...
    @property
    def path(self) -> str: ...
    @property
    def manifest(self) -> Dict[str, Any]: ...
    @property
    def metadata(self) -> Dict[str, str]: ...
    @property
    def channels(self) -> List[Dict[str, Any]]: ...
    @property
    def ground_truth_channels(self) -> List[str]: ...
    def require_chunk_checksums(self, require: bool) -> None: ...
    def verify(self) -> Dict[str, Any]: ...
    def content_digest(self) -> str: ...
    def records(
        self, channel: Optional[str] = ..., limit: Optional[int] = ...
    ) -> List[Dict[str, Any]]: ...
    def arrow(self, channel: str, ground_truth: bool = ...) -> Any: ...
    def table(self, channel: str, ground_truth: bool = ...) -> bytes: ...
    def table_schema(self, channel: str) -> Dict[str, Any]: ...
    def frame_count(self) -> int: ...

def run(
    scenario: Scenario,
    *,
    build_utc: str,
    recording: Optional[str] = ...,
    metrics: bool = ...,
    metric_window_s: float = ...,
) -> Run: ...
def run_twice(scenario: Scenario, *, build_utc: str) -> Tuple[str, str]: ...

class math:
    """The engine's transcendentals. A plug-in uses these instead of Python's ``math``."""

    @staticmethod
    def sin(x: float) -> float: ...
    @staticmethod
    def cos(x: float) -> float: ...
    @staticmethod
    def tan(x: float) -> float: ...
    @staticmethod
    def asin(x: float) -> float: ...
    @staticmethod
    def acos(x: float) -> float: ...
    @staticmethod
    def atan(x: float) -> float: ...
    @staticmethod
    def atan2(y: float, x: float) -> float: ...
    @staticmethod
    def exp(x: float) -> float: ...
    @staticmethod
    def exp2(x: float) -> float: ...
    @staticmethod
    def ln(x: float) -> float: ...
    @staticmethod
    def log10(x: float) -> float: ...
    @staticmethod
    def log2(x: float) -> float: ...
    @staticmethod
    def pow(base: float, exponent: float) -> float: ...
    @staticmethod
    def sqrt(x: float) -> float: ...
    @staticmethod
    def cbrt(x: float) -> float: ...
    @staticmethod
    def hypot(x: float, y: float) -> float: ...
    @staticmethod
    def sinh(x: float) -> float: ...
    @staticmethod
    def cosh(x: float) -> float: ...
    @staticmethod
    def tanh(x: float) -> float: ...
    @staticmethod
    def sin_cos(x: float) -> Tuple[float, float]: ...
    @staticmethod
    def quantize_to(x: float, quantum: float) -> float: ...
    @staticmethod
    def quantize(x: float, decimals: int) -> float: ...
    @staticmethod
    def is_on_grid(x: float, quantum: float) -> bool: ...
    @staticmethod
    def grid_index(x: float, quantum: float) -> int: ...
    @staticmethod
    def sum_ordered(values: Sequence[float]) -> float: ...
    @staticmethod
    def sum_sorted_by_key(pairs: Iterable[Tuple[str, float]]) -> float: ...

class plugins:
    """Views, cards and the family adapters."""

    PROBABILITY_QUANTUM: float

    class Ego:
        actor: int
        vehicle_class: str
        lane: int
        lane_index: int
        s_m: float
        lateral_m: float
        speed_mps: float
        accel_mps2: float
        heading_rad: float
        length_m: float
        width_m: float
        height_m: float
        desired_speed_mps: float
        max_accel_mps2: float
        comfort_decel_mps2: float
        time_headway_s: float
        min_gap_m: float

    class Leader:
        gap_m: float
        speed_mps: float
        accel_mps2: float
        length_m: float
        is_vehicle: bool

    class Lane:
        id: int
        kind: str
        speed_limit_mps: float
        width_m: float
        length_m: float

    class Weather:
        kind: str
        intensity: float
        visibility_m: float
        surface: str

    class DetectorCtx:
        t_ns: int
        node: int

    class Observation:
        subject: int
        kind: str
        confidence: float
        t_ns: int
        def __init__(
            self, subject: int, kind: str, confidence: float, t_ns: int
        ) -> None: ...

    class CarFollowingModel:
        def __init__(self, object: Any) -> None: ...
        @property
        def id(self) -> str: ...
        @property
        def card(self) -> Dict[str, Any]: ...
        @property
        def last_error(self) -> Optional[str]: ...
        def accel(
            self,
            ego_speed_mps: float,
            gap_m: Optional[float] = ...,
            leader_speed_mps: float = ...,
            speed_limit_mps: float = ...,
            is_vehicle: bool = ...,
        ) -> float: ...

    class DetectorModel:
        def __init__(self, object: Any) -> None: ...
        @property
        def id(self) -> str: ...
        @property
        def card(self) -> Dict[str, Any]: ...
        @property
        def last_error(self) -> Optional[str]: ...
        def on_messages(
            self, t_ns: int, node: int, batch: Any
        ) -> List["plugins.Observation"]: ...

    class ReferenceDetector:
        def __init__(self, max_speed_mps: float = ...) -> None: ...
        @property
        def card(self) -> Dict[str, Any]: ...
        def on_messages(
            self, t_ns: int, node: int, batch: Any
        ) -> List["plugins.Observation"]: ...

    @staticmethod
    def validate_card(card: Any) -> Dict[str, Any]: ...
    @staticmethod
    def uncited_parameters(card: Any) -> List[str]: ...

class _conformance:
    """The checks that need the engine's own call path."""

    @staticmethod
    def check_determinism(model: Any) -> Dict[str, Any]: ...
    @staticmethod
    def check_thread_independence(model: Any) -> Dict[str, Any]: ...
    @staticmethod
    def check_dyn_compatibility(model: Any) -> Dict[str, Any]: ...
    @staticmethod
    def check_card(model: Any) -> List[Dict[str, Any]]: ...
    @staticmethod
    def check_quantisation(model: Any, quantum: float = ...) -> Dict[str, Any]: ...
    @staticmethod
    def check_finite(model: Any) -> Dict[str, Any]: ...
