#!/usr/bin/env python3
"""Restrict an E1 detector layout to the loops a reference-count file actually measured.

WHY THIS EXISTS
---------------
``tools/fetch_ingolstadt_counts.py`` sums only the InTAS-matched real detectors at each station.
At a ``comparability = subset`` station some InTAS loop has no real counterpart (SUMO lane-splits
such as ``3100_4_1`` / ``3100_4_2``), so the reference is a LOWER BOUND on that station.

``tools/sumo_realism.py`` groups the modelled side by the E1 ``@name``, i.e. it sums *every* InTAS
loop at the station. Comparing that to a matched-subset reference is apples-to-oranges and biases
the modelled side HIGH by exactly the flow over the unmatched loops.

This tool writes a mapping-only copy of the E1 additional file that keeps only the detectors named
in the reference file's ``station_details[*].matched_detector_ids``. Feeding that copy to
``sumo_realism.py --det-add`` makes both sides sum the SAME physical loops. Detectors that are
dropped are not silently folded into another station: they simply vanish from the mapping, and
``sumo_realism`` then keys them by their own detector id, so they land in ``stations_only_in_modelled``
and are excluded from every gate.

For a ``comparability = exact`` station the matched set is the full InTAS set, so filtering is a
no-op there and the headline number is unaffected.

OUTPUT IS MAPPING-ONLY. Do not hand the result to SUMO as an ``--additional-files`` entry: the
detector ``file`` attributes are rewritten to a placeholder and the unnamed gate counters are gone.

LICENCE: the reference file this reads is SAVeNoW / Stadt Ingolstadt data whose licence is NOT
formally stated. This tool copies no count values, only detector ids, but do not commit either.
"""
from __future__ import annotations

import argparse
import json
import sys
import xml.etree.ElementTree as ET
from pathlib import Path

PLACEHOLDER_FILE = "mapping_only_do_not_run.xml"
HEADER = (
    '<?xml version="1.0" encoding="UTF-8"?>\n'
    "<!-- GENERATED by tools/e1_match_filter.py. MAPPING ONLY, NOT A RUNNABLE ADDITIONAL FILE.\n"
    "     Kept: the E1 loops that {ref} reports as measured (matched_detector_ids).\n"
    "     Dropped: {n_drop} of {n_all} e1Detector entries.\n"
    "     Purpose: make the modelled side sum the same physical loops as the reference. -->\n"
)


def load_matched(ref_path: Path) -> tuple[set[str], dict[str, list[str]]]:
    """``{detector_id}``, plus ``{station: [dropped detector ids]}`` from a ref-counts JSON."""
    doc = json.loads(ref_path.read_text(encoding="utf-8"))
    details = doc.get("station_details")
    if not isinstance(details, dict) or not details:
        raise SystemExit(
            f"{ref_path}: no 'station_details' block. This tool needs the rich JSON written by "
            f"tools/fetch_ingolstadt_counts.py, not a bare {{station: count}} file.")
    emitted = set(doc.get("stations") or {})
    keep: set[str] = set()
    dropped: dict[str, list[str]] = {}
    for sid, det in details.items():
        if sid not in emitted:
            continue                      # station not in this reference file at all
        keep.update(str(d) for d in det.get("matched_detector_ids") or [])
        un = [str(d) for d in det.get("unmatched_intas_detector_ids") or []]
        if un:
            dropped[sid] = sorted(un)
    if not keep:
        raise SystemExit(f"{ref_path}: no matched_detector_ids anywhere; nothing to keep.")
    return keep, dropped


def filter_add(add_path: Path, keep: set[str]) -> tuple[ET.ElementTree, int, int, list[str]]:
    tree = ET.parse(add_path)
    root = tree.getroot()
    n_all = n_kept = 0
    # root.iter() already yields root itself exactly once, then every descendant
    for parent in list(root.iter()):
        for el in list(parent):
            if el.tag not in ("e1Detector", "inductionLoop"):
                continue
            n_all += 1
            if str(el.get("id")) in keep:
                n_kept += 1
                if el.get("file"):
                    el.set("file", PLACEHOLDER_FILE)
            else:
                parent.remove(el)
    seen = {el.get("id") for el in root.iter() if el.tag in ("e1Detector", "inductionLoop")}
    missing_parent = sorted(k for k in keep if k not in seen)
    return tree, n_all, n_kept, missing_parent


def main(argv=None) -> int:
    p = argparse.ArgumentParser(
        description="Restrict an E1 layout to the loops a reference-count file measured.",
        epilog="Mapping only. Never pass the output to SUMO as an additional file.")
    p.add_argument("--det-add", required=True, help="InTAS_E1.add.xml (read-only)")
    p.add_argument("--ref-counts", required=True,
                   help="ref-counts JSON from tools/fetch_ingolstadt_counts.py "
                        "(needs station_details.matched_detector_ids)")
    p.add_argument("--out", required=True, help="filtered mapping file to write")
    a = p.parse_args(argv)

    add_path, ref_path, out_path = Path(a.det_add), Path(a.ref_counts), Path(a.out)
    if "--" in str(out_path):
        p.error("refusing to write to a path containing a double dash: SUMO embeds its command "
                "line in an XML comment, where '--' is illegal")
    keep, dropped = load_matched(ref_path)
    tree, n_all, n_kept, missing = filter_add(add_path, keep)

    out_path.parent.mkdir(parents=True, exist_ok=True)
    body = ET.tostring(tree.getroot(), encoding="unicode")
    out_path.write_text(
        HEADER.format(ref=ref_path.name, n_drop=n_all - n_kept, n_all=n_all) + body + "\n",
        encoding="utf-8")

    print(f"layout    {add_path}  ({n_all} e1Detector entries)")
    print(f"reference {ref_path.name}")
    print(f"kept      {n_kept}  dropped {n_all - n_kept}")
    for sid in sorted(dropped):
        print(f"  {sid:<6} dropped {len(dropped[sid])}: {', '.join(dropped[sid])}")
    if missing:
        print(f"WARNING: {len(missing)} matched detector id(s) are not in the layout at all: "
              f"{', '.join(missing[:10])}", file=sys.stderr)
    print(f"wrote     {out_path.resolve()}")
    print("MAPPING ONLY: do not pass this file to SUMO as an --additional-files entry.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
